require("prototypes.entities.circuit-connector-sprites")

require("prototypes.categories.group")
require("prototypes.categories.recipe")
require("prototypes.categories.military")
require("prototypes.categories.machine")
require("prototypes.categories.energy")
require("prototypes.categories.intermediate")

require("prototypes.entities.fission-reactor-chest-entity")
require("prototypes.entities.fission-reactor-entity")
require("prototypes.entities.fission-reactor-steam-generator")
require("prototypes.entities.fission-reactor-steam-generator-internals")
require("prototypes.entities.fission-reactor-turbine-generator")
require("prototypes.entities.fission-reactor-turbine-generator-internals")
require("prototypes.entities.projectiles")
require("prototypes.entities.utility-entities")
require("prototypes.entities.water-gen-prototypes")

require("prototypes.fluids.fluid")
require("prototypes.fluids.fuel-reprocessing-fluid")
require("prototypes.fluids.uranium-hexafluoride-fluid")

require("prototypes.items.ammo")
require("prototypes.items.fission-reactor-chest-item")
require("prototypes.items.fission-reactor-item")
require("prototypes.items.fission-reactor-steam-generator-item")
require("prototypes.items.fission-reactor-steam-generator-internals-item")
require("prototypes.items.fission-reactor-turbine-generator-item")
require("prototypes.items.fission-reactor-turbine-generator-internals-item")
require("prototypes.items.fuel-assembly-item")
require("prototypes.items.spent-fuel-assembly-item")
require("prototypes.items.item")
require("prototypes.items.uranium-pellet-item")

require("prototypes.recipes.ammo-recipe")
require("prototypes.recipes.fuel-assembly-recipe")
require("prototypes.recipes.fluid-recipe")
require("prototypes.recipes.fuel-reprocessing-fluid-recipe")
require("prototypes.recipes.nuclear-fission-reactor-recipe")
require("prototypes.recipes.nuclear-fission-reactor-steam-generator-recipe")
require("prototypes.recipes.nuclear-fission-reactor-turbine-generator-recipe")
require("prototypes.recipes.uranium-hexafluoride-recipe")
require("prototypes.recipes.uranium-pellet-recipe")
require("prototypes.recipes.utility-recipe")

require("prototypes.resources.resources")

require("prototypes.technologies.technology")

require("prototypes.tiles.noise-layers")

require("prototypes.autoplace-controls")