data:extend({
  {
    type = "fluid",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0.965, b=0.561},
    flow_color = {r=1, g=0.965, b=0.661},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    --order = "a[fluid]-g[uranium-hexafluoride]",
    name = "uranium-hexafluoride-01",
    icon = "__UraniumPower__/graphics/icons/uranium-hexafluoride-01.png",
	group = "uranium",
    subgroup = "uranium-fluids",
	order = "a"
  },
  {
    type = "fluid",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0.965, b=0.561},
    flow_color = {r=1, g=0.965, b=0.661},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    --order = "a[fluid]-g[uranium-hexafluoride]",
    name = "uranium-hexafluoride-02",
    icon = "__UraniumPower__/graphics/icons/uranium-hexafluoride-02.png",
	group = "uranium",
    subgroup = "uranium-fluids",
	order = "a"
  },
  {
    type = "fluid",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0.965, b=0.561},
    flow_color = {r=1, g=0.965, b=0.661},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    --order = "a[fluid]-g[uranium-hexafluoride]",
    name = "uranium-hexafluoride-03",
    icon = "__UraniumPower__/graphics/icons/uranium-hexafluoride-03.png",
	group = "uranium",
    subgroup = "uranium-fluids",
	order = "a"
  },
  {
    type = "fluid",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0.965, b=0.561},
    flow_color = {r=1, g=0.965, b=0.661},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    --order = "a[fluid]-g[uranium-hexafluoride]",
    name = "uranium-hexafluoride-04",
    icon = "__UraniumPower__/graphics/icons/uranium-hexafluoride-04.png",
	group = "uranium",
    subgroup = "uranium-fluids",
	order = "a"
  },
  {
    type = "fluid",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0.965, b=0.561},
    flow_color = {r=1, g=0.965, b=0.661},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    --order = "a[fluid]-g[uranium-hexafluoride]",
    name = "uranium-hexafluoride-05",
    icon = "__UraniumPower__/graphics/icons/uranium-hexafluoride-05.png",
	group = "uranium",
    subgroup = "uranium-fluids",
	order = "a"
  },
  {
    type = "fluid",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0.965, b=0.561},
    flow_color = {r=1, g=0.965, b=0.661},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    --order = "a[fluid]-g[uranium-hexafluoride]",
    name = "uranium-hexafluoride-06",
    icon = "__UraniumPower__/graphics/icons/uranium-hexafluoride-06.png",
	group = "uranium",
    subgroup = "uranium-fluids",
	order = "a"
  },
  {
    type = "fluid",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0.965, b=0.561},
    flow_color = {r=1, g=0.965, b=0.661},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    --order = "a[fluid]-g[uranium-hexafluoride]",
    name = "uranium-hexafluoride-07",
    icon = "__UraniumPower__/graphics/icons/uranium-hexafluoride-07.png",
	group = "uranium",
    subgroup = "uranium-fluids",
	order = "a"
  },
  {
    type = "fluid",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0.965, b=0.561},
    flow_color = {r=1, g=0.965, b=0.661},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    --order = "a[fluid]-g[uranium-hexafluoride]",
    name = "uranium-hexafluoride-08",
    icon = "__UraniumPower__/graphics/icons/uranium-hexafluoride-08.png",
	group = "uranium",
    subgroup = "uranium-fluids",
	order = "a"
  },
  {
    type = "fluid",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0.965, b=0.561},
    flow_color = {r=1, g=0.965, b=0.661},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    --order = "a[fluid]-g[uranium-hexafluoride]",
    name = "uranium-hexafluoride-09",
    icon = "__UraniumPower__/graphics/icons/uranium-hexafluoride-09.png",
	group = "uranium",
    subgroup = "uranium-fluids",
	order = "a"
  },
  {
    type = "fluid",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0.965, b=0.561},
    flow_color = {r=1, g=0.965, b=0.661},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    --order = "a[fluid]-g[uranium-hexafluoride]",
    name = "uranium-hexafluoride-10",
    icon = "__UraniumPower__/graphics/icons/uranium-hexafluoride-10.png",
	group = "uranium",
    subgroup = "uranium-fluids",
	order = "a"
  },

})
