data:extend(
{
	{
		type = "item",
		name = "turbine-generator-feed-water-box",
		icon = "__UraniumPower__/graphics/entity/turbine-generator-internals/feedwaterboxicon.png",
		flags = {"goes-to-quickbar"},
		subgroup = "uranium-raw-resource",
		order = "d[uraninite]",
		stack_size = 50,
		place_result = "turbine-generator-feed-water-box",
	},

	{
		type = "item",
		name = "turbine-generator-cold-leg-box",
		icon = "__UraniumPower__/graphics/entity/turbine-generator-internals/coldlegicon.png",
		flags = {"goes-to-quickbar"},
		subgroup = "uranium-raw-resource",
		order = "d[uraninite]",
		stack_size = 50,
		place_result = "turbine-generator-cold-leg-box",
	},
	{
		type = "item",
		name = "turbine-generator-low-p-steam-box-01",
		icon = "__UraniumPower__/graphics/entity/turbine-generator-internals/steamreservoiricon.png",
		flags = {"goes-to-quickbar"},
		subgroup = "uranium-raw-resource",
		order = "d[uraninite]",
		stack_size = 50,
		place_result = "turbine-generator-low-p-steam-box-01",
	},
	{
		type = "item",
		name = "turbine-generator-low-p-steam-box-02",
		icon = "__UraniumPower__/graphics/entity/turbine-generator-internals/steamreservoiricon.png",
		flags = {"goes-to-quickbar"},
		subgroup = "uranium-raw-resource",
		order = "d[uraninite]",
		stack_size = 50,
		place_result = "turbine-generator-low-p-steam-box-02",
	},
	{
		type = "item",
		name = "turbine-generator-low-p-steam-box-03",
		icon = "__UraniumPower__/graphics/entity/turbine-generator-internals/steamreservoiricon.png",
		flags = {"goes-to-quickbar"},
		subgroup = "uranium-raw-resource",
		order = "d[uraninite]",
		stack_size = 50,
		place_result = "turbine-generator-low-p-steam-box-03",
	},
	{
		type = "item",
		name = "turbine-generator-low-p-steam-box-04",
		icon = "__UraniumPower__/graphics/entity/turbine-generator-internals/steamreservoiricon.png",
		flags = {"goes-to-quickbar"},
		subgroup = "uranium-raw-resource",
		order = "d[uraninite]",
		stack_size = 50,
		place_result = "turbine-generator-low-p-steam-box-04",
	},

})