data:extend({
  {
    type = "item",
    flags = {"goes-to-main-inventory"},
    subgroup = "uranium-products",
    order = "a-1",
    stack_size = 1,
    name = "fuel-assembly-01",
    icon = "__UraniumPower__/graphics/icons/fuel-assembly-01.png",
  },
  {
    type = "item",
    flags = {"goes-to-main-inventory"},
    subgroup = "uranium-products",
    order = "a-2",
    stack_size = 1,
    name = "fuel-assembly-02",
    icon = "__UraniumPower__/graphics/icons/fuel-assembly-02.png",
  },
  {
    type = "item",
    flags = {"goes-to-main-inventory"},
    subgroup = "uranium-products",
    order = "a-3",
    stack_size = 1,
    name = "fuel-assembly-03",
    icon = "__UraniumPower__/graphics/icons/fuel-assembly-03.png",
  },
  {
    type = "item",
    flags = {"goes-to-main-inventory"},
    subgroup = "uranium-products",
    order = "a-4",
    stack_size = 1,
    name = "fuel-assembly-04",
    icon = "__UraniumPower__/graphics/icons/fuel-assembly-04.png",
  },
  {
    type = "item",
    flags = {"goes-to-main-inventory"},
    subgroup = "uranium-products",
    order = "a-5",
    stack_size = 1,
    name = "fuel-assembly-05",
    icon = "__UraniumPower__/graphics/icons/fuel-assembly-05.png",
  },
  {
    type = "item",
    flags = {"goes-to-main-inventory"},
    subgroup = "uranium-products",
    order = "a-6",
    stack_size = 1,
    name = "fuel-assembly-06",
    icon = "__UraniumPower__/graphics/icons/fuel-assembly-06.png",
  },
  {
    type = "item",
    flags = {"goes-to-main-inventory"},
    subgroup = "uranium-products",
    order = "a-7",
    stack_size = 1,
    name = "fuel-assembly-07",
    icon = "__UraniumPower__/graphics/icons/fuel-assembly-07.png",
  },
  {
    type = "item",
    flags = {"goes-to-main-inventory"},
    subgroup = "uranium-products",
    order = "a-8",
    stack_size = 1,
    name = "fuel-assembly-08",
    icon = "__UraniumPower__/graphics/icons/fuel-assembly-08.png",
  },
  {
    type = "item",
    flags = {"goes-to-main-inventory"},
    subgroup = "uranium-products",
    order = "a-9",
    stack_size = 1,
    name = "fuel-assembly-09",
    icon = "__UraniumPower__/graphics/icons/fuel-assembly-09.png",
  },
  {
    type = "item",
    flags = {"goes-to-main-inventory"},
    subgroup = "uranium-products",
    order = "a-9a",
    stack_size = 1,
    name = "fuel-assembly-10",
    icon = "__UraniumPower__/graphics/icons/fuel-assembly-10.png",
  },

})
